### ISSUE TITLE
States handling

### ISSUE THREAD

**Issue by gasperjug** [MaxIV-KitsControls/Libera-SinglePassE#10]
Does the Tango DS needs to handle some states for the Libera Single Pass E?
- Which states and how?

**Comment by hardion** [comment]
From the device of the old platform, these states are defined :
ON  The Libera box is up and running
UNKNOWN No possible communication with the Libera box
FAULT   The Libera box is in Fault

**Comment by gasperjug** [comment]
OK. Thnx.
This will be closed.
