### ISSUE TITLE
1 - Tango version

### ISSUE THREAD

**Issue by hinxx** [MaxIV-KitsControls/Libera-SinglePassE#12]
What version of Tango library should be used by the Libera SinglePassE Tango DS?

Tango 7 or Tango 8.

FYI, we managed to get the DS compiled and running using either versions of Tango library so far.

**Comment by hardion** [comment]
Until the release of the official DEB package of the version 8, you should use the current one with Tango 7 on the Libera.

**Comment by hinxx** [comment]
Agreed!
