### ISSUE TITLE
1 - Tango deployment location on the Libera unit

### ISSUE THREAD

**Issue by hinxx** [MaxIV-KitsControls/Libera-SinglePassE#13]
Where should Tango libraries be installed on the Libera unit?
Do you have a specific location / folder in mind?
Are there any guidelines we need to follow?

FYI, Libera BASE software is installed in /opt/libera, application daemon is started using /etc/init.d/libera startup script. Software (including the Libera BASE) packages is managed by the Debian package management system (apt, dpkg,..). IOW, all software that gets installed on the Libera unit is (pre-)packaged into DEB packages and then deployed using standard methods that the Ubutu distribution provides.

**Comment by hardion** [comment]
Deb package is the best solution. Follow the instruction for Ubuntu 10.04 described here : https://www.tango-controls.org/download. In this case you have nothing to do.

**Comment by hinxx** [comment]
Nice one.

Will use the DEBs found on the mentioned page.
