### ISSUE TITLE
2 - Documentation

### ISSUE THREAD

**Issue by hinxx** [MaxIV-KitsControls/Libera-SinglePassE#14]
I'm afraid we haven't discussed the documentation part much.

Looking at what the current Libera Single Pass Tango DS provides here, http://www.esrf.eu/computing/cs/tango/tango_doc/ds_doc/tango-ds/BeamDiag/libera-sp/user_guide.pdf, I think we might be able to produce such an output with relatively small effort.

What is your view of this matter?

**Comment by hardion** [comment]
Good point.
This documentation is generated automatically by Pogo. But no magic here you have to fill the description of each attributes, commands, state ... 
You could use Pogo to help you to fill the different fields.

**Comment by hinxx** [comment]
Looking at the POGO generated HTML it is quite obvious how and from where the document is generated.

What is generated will be checked so that there are no references to non-existent attributes, properties and concepts that were imported from SinglePass Tango DS. Where needed new descriptions will be introduced.

Let me know if you need more thorough description of some feature/attribute/command/etc..

**Comment by hinxx** [comment]
Closing..
