### ISSUE TITLE
1 - Tango starter

### ISSUE THREAD

**Issue by hinxx** [MaxIV-KitsControls/Libera-SinglePassE#15]
There is little information that we have about this "Tango starter" utility(?).

Can you provide more info, please?

Is there a documentation available on how to use it.. and most importantly a) how do you use it, and b) how do you want us to use it :)

**Comment by hardion** [comment]
This documentation should give you some information about the Starter and Astor (GUI on top) : http://www.esrf.eu/computing/cs/tango/tango_doc/tools_doc/astor_doc/index.html
As you run a Tango Database on the Libera for your dev&test, you could register a Starter locally without blocking the future integration in the customer Database. (Everything is kept in the Tango Database)

**Comment by hardion** [comment]
In the future I could give you some python script to install the starter automatically.
By this way you could provide to your customer these scripts...
