### ISSUE TITLE
2 - Tango system user

### ISSUE THREAD

**Issue by hinxx** [MaxIV-KitsControls/Libera-SinglePassE#16]
As you pointed out in one of the e-mails, Tango DS is usually started under a separate user on a Linux system - username "tango".

What is this "tango" user allowed to do?
What permissions does it have?
Does it own its home folder (eg. /home/tango)?
Is there any data (files, folders, configuration) that "tango" user needs to have access to (probably located in its home folder)?

FYI, our daemon is ran under the "root" account (but this should not be an issue since this is the only process doing some real work - IOW, there is no "real" users).

**Comment by hardion** [comment]
It might be slightly different with the RPM we supply.
So by installing the deb packages you could check by yourself.

**Comment by hinxx** [comment]
OK, since we agree that the Tango7 DEBs will be used on the unit, I'll go ahead and install those and see what comes out of that.

Are the differences between DEBs and RPMs of any importance to you? E.g. do you have scripts/code/processes that rely on the "tango" user name/login for Tango DS powered boxes? .. and by not using the "tango" user on our box you end up with inconsistent control system environment.

**Comment by hinxx** [comment]
Running LiberaSinglePassE on the unit with PPA Tango7 DEBs installed was successfully tested.
