### ISSUE TITLE
1 - Introduce LiberaBoard property

### ISSUE THREAD

**Issue by hinxx** [MaxIV-KitsControls/Libera-SinglePassE#2]
Under Platform B Tango Device server binary will be running on the Libera unit itself.
In fact, since we can have up to 4 processing boards present in the unit, up to 4 Tango Device servers will be running, each handling data from a separate processing board - acting as a independent Tango Device server.

AFAIK, instance strings (passed on the command line) must be unique to the Tango Database (correct me if I'm wrong). That being said we must ensure that the LiberaSinglePassE Tango Device server(s) are started using a well defined and still unique identifier for instance name.

We propose that LiberaSinglePassE instance names are in the following format:
 aaa.bbb.ccc.ddd-nnn

where "aaa.bbb.ccc.ddd" is the Libera unit IP address and "nnn" stands for one of the 4 processing boards.

Using this scheme operator can easily identify Tango Device server IP address and number of boards it actually has installed.

Do you have any comments/questions regarding this matter?

**Comment by hardion** [comment]
The title seems almost not related to the content.
Anyway if the purpose is to connect the Tango device with the correct board, defines the property "LiberaBoard" should do the job.
Regarding the instance name, each institut has its own convention. In any case the device has access to the instance name. Usually we start the instance with the Tango Starter and by this way we could define any instance name.

**Comment by hinxx** [comment]
Let me try to elaborate the board concept.

The platform can house several HW boards. Besides the processing boards (1 - 4) there exists a timing board and processor board. IOW, a single processing board can be seen as a separate beam processor (timing and processor boards are shared among all processing boards).

Since the requirement was to have one Tango device server per a processor board (beam processor), we need to tell the Tango process which board it should use for data acquisition.

For this purpose LiberaBoard property was introduced - I'm not sure if it is the right choice to use property here, but it was best I could do with my limited Tango knowledge.

Regarding the instance name, in the Tango device server code we will not try to handle/rely on its value.

**Comment by hardion** [comment]
Perfect

**Comment by gasperjug** [comment]
OK. Thnx. Closing.

**Comment by gasperjug** [comment]
For the event receiver (timing) board the property will be hard coded in the code to evrx2, because every chassis will host one event receiver board and its position is known and fixed - slot 2.

This will not be a property used in database.

**Comment by hardion** [comment]
OK
