### ISSUE TITLE
3 - Tango and 64-bit data types

### ISSUE THREAD

**Issue by hinxx** [MaxIV-KitsControls/Libera-SinglePassE#20]
I've noticed that POGO from Tango7 does not generate (support?)  the 64-bit integer types .. correctly. Using POGO and selecting DevULong64 or DevLong64 data type  results in code that uses 32-bit data type (DevULong or DevLong).

Is this a known issue?

**Comment by hardion** [comment]
This is a bug in pogo that comes with Tango7 ...
If you change the type in the code, it will be overridden at the next code generation I guess?

**Comment by hinxx** [comment]
Yes, manual changes are overridden at next POGO code generation.

It is not a problem for us now, we just wanted to be sure that it is a Tango issue.
