### ISSUE TITLE
1 - Fans speeds on LSPE

### ISSUE THREAD

**Issue by gasperjug** [MaxIV-KitsControls/Libera-SinglePassE#6]
For the fans speeds we suggest to remain at 2 attributes:
- left side
- right side
- Each side has 3 fans, so the minimal of each side would be presented/exposed to the operator.

With this:
- the diagnostics purpose is remained (operator identifying the fail of fan (value 0) or operation ok)
- we are not increasing the number of attributes for fans speeds compared to the existing Tango DS for Libera Brilliance Single Pass.

Is this acceptable?

**Comment by hinxx** [comment]
Gasper, i think we need to update this proposal.

**Comment by gasperjug** [comment]
Updated. Thanks.

**Comment by gasperjug** [comment]
Described suggestion has been implemented.

**Comment by gasperjug** [comment]
Would it be acceptable to rename the attributes from:
- Fan1Speed to Left fans speed and
- Fan2Speed to Right fans speed?

**Comment by hardion** [comment]
The value compared breaking the compatibility is low.
Just update the description should be sufficient. 
Unless you consider that give more sense for your future/other customer.

**Comment by gasperjug** [comment]
OK.
- Minimal value of 3 fans speed exposed.
  Naming:
- Fan1Speed and
- Fan2Speed remains.
  Closing.
