### ISSUE TITLE
1 - Activation of Tango DS

### ISSUE THREAD

**Issue by gasperjug** [MaxIV-KitsControls/Libera-SinglePassE#7]
The Tango DS will start at startup of the instrument.

Do you want to:
- control its activation/connection (having the control system to activate it through some script or manually by the operator) or
- can it also activate/connect automatically at the startup?

**Comment by hardion** [comment]
Usually the Tango devices are started by another service so-called "Tango Starter". 
At the installation of the Libera we have to set the address of the Tango Database (TANGO_HOST).
So the first option seems better.

**Comment by tomaz-beltram** [comment]
Additional question just to make sure we understand the desired behavior correctly.

The "Tango Starter" will start the device server processes on all instruments with appropriate instance ID as the first command line argument? This parameter is related to the device/board as discussed in the issue #2? There will be up to four such processes on each instrument. 

Each device server process will  execute the init_device() function and connect to appropriate board. If successful it will put the device in the ON state.

**Comment by hardion** [comment]
Exactly.
More precision : Each Libera (not BPM) will host a Starter which start the processes locally with the instance ID.
From the #2 : You could choose any naming convention for the instance ID. It doesn't mean that once installed in the Synchrotron, the instance ID will be the same. Only the LiberaBoard property will be the parameter to distinguish to which board to connect.

**Comment by hinxx** [comment]
This is acceptable and sane.

**Comment by hardion** [comment]
Another precision : The Tango Starter is also a Tango Device with a particularity : the instance name is important because it should be equivalent to the host name. And I suppose that each libera will have a specific host name on the customer site.

**Comment by hinxx** [comment]
Since we do not have much experience in the Tango environment and DS use cases, can we expect that the Tango community will be able to most efficiently tailor the LiberaSinglePassE startup process themselves?

IOW, we do not want to fiddle too much with the TangoStarter process, and possibly providing impractical solution out-of-the box - OTOH, LiberaSinglePassE should nevertheless play nicely with TangoStarter.

**Comment by hardion** [comment]
Agree to let the customer configures the Tango Starter
