### ISSUE TITLE
1 - Example needed: Group request and coherence of data in Libera system

### ISSUE THREAD

**Issue by gasperjug** [MaxIV-KitsControls/Libera-SinglePassE#8]
Your question:
- Is the system supporting group request or data as a structure ? This could be beneficial for the polling strategy.

Our answer:
- If with the polling strategy was thought that with single request more than one parameter is read (optimizing the data transfer over the net), it is not available in our SW.
- If here is meant access to the parameters of the transactions, this is not available in our SW. Also there are not available data structures; iREG node is always basic data type.

Your question to our answer:
- So in this case how could we guarantee the coherence of the data ? Does your system send one event by parameters ?

Our answer:
- Streams or data that units are sending out are synchronized and that is the instruments/data property by design. For the parameters they are used for setting controls of the instrument.

Please tell us for which parameters/data are you concerned not to be coherent and why?
It will be easier to agree on the solution/implementation if we will have the example.

**Comment by hardion** [comment]
With Tango the client have the possibility to request several attributes in one request to be sure the data are coherent in time each other.
If I request the values of the attributes Left, Right and TriggerCounter, I should have the data from the same TriggerCounter number (and not the Left values of the trigger-1)

I would avoid the update of data during a reading request.

**Comment by hardion** [comment]
Until the data are updated in the always_executed_hook there is no problem of incoherence
