### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by gasperjug** [MaxIV-KitsControls/Libera-SinglePassE#9]
What should the Tango DS do when error is issued?
- Remain in present state, change state – to which, reset?

**Comment by hardion** [comment]
The state should be in FAULT.
The Reset command seems the acknowledgement to change the state to ON.

If you look at the StateMachine of the old device : http://tango-ds.cvs.sourceforge.net/viewvc/tango-ds/BeamDiag/i-tech-single-pass/LiberaSPStateMachine.cpp?view=markup
you will find among other thing :
- Reset disabled for Tango::ON and Tango::UNKNOWN
- ResetTrigger disabled for the state Tango::UNKNOWN and Tango::FAULT

**Comment by gasperjug** [comment]
OK. Thnx.
This will be closed.
